### ISSUE TITLE
Helper library for porting code which uses a lot of reflection logic

### ISSUE THREAD

**Issue by StefH** [davidfowl/NetStandard#4]
As known, a lot of reflection functionality like Type.BaseType is not available anymore in **dnxcore50 / NetStandard**. A possible solution would be to use: `Type.GetTypeInfo().BaseType`.

I encountered this issue a lot while converting some of my projects from net40/45 to dnxcore5/NetStandard.

I solved this compatibility issue by create a helper library (https://github.com/StefH/ReflectionBridge) : which functions as a bridge to some reflection functionality.

In my normal libraries, I just rewrite all calls from `Type.BaseType` to `Type.BaseType()` (so instead of invoking a property, I create an extension method like this:

``` c#
        public static Type BaseType(this Type type)
        {
#if REFLECTIONBRIDGE && (!(NET40 || NET35 || NET20))
            return type.GetTypeInfo().BaseType;
#else
            return type.BaseType;
#endif
        }
```

With this new helper functionality, I don't need any ifdefs in my main code, this is solved in the extension method.

Also discussed here [https://github.com/Microsoft/dotnet-apiport/issues/268].

**Comment by davidfowl** [comment]
This is pretty sweet! I hope we can provide something like this out of the box...

**Comment by StefH** [comment]
According to the comment from dotnet-apiport, this will not be build.

So maybe you can take a look at my helper library and see if we can improve some code or usability. And if you think it's 'production-ready-code', maybe you can suggest to use this library in your manuals in defined here?

**Comment by davidfowl** [comment]
@StefH I'm thinking you should turn this into a source only package. It'll make it more attractive to use since people don't want a dependency on ReflectionBridge hanging around in their packages.

**Comment by jonorossi** [comment]
> In my normal libraries, I just rewrite all calls from Type.BaseType to Type.BaseType() (so instead of invoking a property, I create an extension method like this:

We've had great success in porting Castle DynamicProxy with a simple [`GetTypeInfo` extension method to emulate .NET 4.5+](https://github.com/castleproject/Core/blob/netcore/src/Castle.Core/Compatibility/IntrospectionExtensions.cs) on .NET 3.5/4.0, I actually got the idea when I looked at the `IntrospectionExtensions` class. One of the reasons I chose this option is that in the future when we drop support for .NET 3.5/4.0 we just remove the extension method as our actual code doesn't change because on .NET 4.5+ and .NET Core we are actually using the BCL's real APIs not a shim.

Because DynamicProxy is reflection heavy there were a very small number of places this shim doesn't fully cover, we've got a couple of other extension methods for them also in the [`Compatibility` directory](https://github.com/castleproject/Core/tree/netcore/src/Castle.Core/Compatibility), and I've logged two issues to get APIs added that we need to get rid of the `NetCoreReflectionExtensions` class where we aren't using the real API.

**Comment by StefH** [comment]
@jonorossi : nice idea.
You actually build extensions to support the older platforms when your code is actually NetCore.
In my case, I build the extensions the other way around.

**Comment by jonorossi** [comment]
@StefH yep, as well as .NET 4.5/4.6 since they support the new reflection API. Last year I saw others creating extension methods like yours for this functionality which I didn't like very much, I thought if I'm going to make source code changes anyway (adding parenthesis) I might as well move our codebase forward rather than sideways.

**Comment by weshaggard** [comment]
@jonorossi your approach is definitely an interesting one. We (.NET Core team) may consider doing something like that to support the older (<.NET 4.5) source compat.

**Comment by jonorossi** [comment]
@weshaggard thanks. The code is licensed under the Apache 2.0 license so borrow away. It is all pretty simple, but let me know if you've got any questions or have any feedback for us to improve.

**Comment by StefH** [comment]
@jonorossi it seems that the old GetType() will be back, to make porting easier.

See this link: https://blogs.msdn.microsoft.com/dotnet/2016/05/27/making-it-easier-to-port-to-net-core/

I wonder when this will be available.

A lot of changes are happening now and will be in the future. I hope that the final .net core is really what the users en microsoft had in mind.

**Comment by jonorossi** [comment]
@StefH thanks, yer I saw that yesterday and wondered what the changes will be.

Personally I liked the changes to evolve the Reflection API to enable many other scenarios including AOT. I can't imagine the .NET team would want to revert to the class hierarchy that .NET Framework has, maybe they'll just implement shim properties back on Type with the implementation in .NET Core staying as it is today, so obviously not 100% binary compatible.

Will also be interesting to see what they do with the mscorlib vs System.Runtime based API, things are definitely going to be unsettled for a while, I do wonder how much conditional compilation we can remove from our Castle Core .NET Core port for missing features or just revert some API usages where we had to pick suboptimal alternatives.
